# Generated by Django 4.2.7 on 2023-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gatepasses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gatepass",
            name="description",
            field=models.TextField(max_length=300),
        ),
    ]
