# Generated by Django 4.2.7 on 2023-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_file", models.FileField(upload_to="assetfiles/")),
                ("description", models.CharField(max_length=5000)),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
