# Generated by Django 4.2.8 on 2023-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=300)),
                ("asset_file", models.FileField(upload_to="assetfiles/")),
                ("date_created", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
